# Generated by Django 5.1.4 on 2025-01-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='warranty',
            new_name='expiry',
        ),
    ]
